### ISSUE TITLE
New Store Request

### ISSUE THREAD

**Issue by blastbeatsvinyl** [line72/usbmdistros#2]
Hi there - we are a US-based vinyl shop with a good black metal selection. We focus only on metal vinyl. https://blastbeatsvinyl.com/collections/black-metal

Thanks for your consideration!

**Comment by line72** [comment]
Sure, it should be pretty straight-foward, as it looks like you use shopify, which I already have a parser for.

**Comment by blastbeatsvinyl** [comment]
Yes, indeed shopify. Please let me know if there is anything I can do on my
side to help. Really appreciate all the work you do to make blackmetal more
accessible in the US.

**Comment by line72** [comment]
This has been added!

**Comment by blastbeatsvinyl** [comment]
Thank you so much - very much appreciated. We are now adding to a of black
metal to the catalog!
